# 下载链接，定期维护
# https://releases.mattermost.com/5.24.1/mattermost-team-5.24.1-linux-amd64.tar.gz
# https://releases.mattermost.com/5.23.1/mattermost-5.23.1-linux-amd64.tar.gz
# mattermost_download_url: "https://releases.mattermost.com/5.26.2/mattermost-5.26.2-linux-amd64.tar.gz"
# mattermost_download_url: "https://releases.mattermost.com/5.31.0/mattermost-5.31.0-linux-amd64.tar.gz"
mattermost_download_url: "https://releases.mattermost.com/5.34.2/mattermost-5.34.2-linux-amd64.tar.gz"

mattermost_db_user: "mattermost"
mattermost_db_password: "123456"
mattermost_db_name: "mattermost"
